name: 鸣潮签到

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches:
  #    - master
  schedule:
    - cron: "5 21 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run script
      env: 
        COOKIE: eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVkIjoxNzIyNDczNDg1MTg1LCJ1c2VySWQiOjE1MDA0NDk0fQ.Td26GEbjUGdASwHl6spwogXlyI5pLJPUojJinyyqhG0
        devCode: 3e1971c0-cf60-4d31-a415-175260f8b224
      run: python mcMain.py
